Get rid of For loop
InstituteforDiseaseModeling/PACE-HRH pull request #204
Opened 2022-10-19 20:51 UTC by MeWu-IDM

@RHull-IDM I wrote the "get_mortality" from results which does not need to loop over each trials, I tried this and I think the results should be the same as your calculation, let me know if you have queations.
I also found mixed use of dplyr and plyr sometimes cause issues so I think it's better specifying namespace if both are used.

2022-10-24 20:48 UTC, MeWu-IDM commented
@celiot-IDM this was what I mentioned in the meeting, it'll be good if we have a function to return mortality/fertility for all trials

2022-10-25 21:22 UTC, celiot-IDM requested changes
See suggested change ...

2022-10-25 21:22 UTC, celiot-IDM commented on analysis_scripts/Run_Sim_Plot_Population.R
> +    inner_join(agebands)
Here's a faster way to generate the all_trials_matrix dataframe (albeit with slightly different column and sort orders):

```
trials <- names(results)
l <- lapply(trials, function(trial){
  t <- results[[trial]][["PopulationRates"]][[categoryName]][["ratesMatrix"]]
  t <- reshape2::melt(t, varnames = c("Label", "Year"), value.name = "MortalityRate")
  t$Trial = rep(trial, nrow(t))
  return(t)
})

all_trials_matrix <- data.table::rbindlist(l)
all_trials_matrix$Label <- as.character(all_trials_matrix$Label)
all_trials_matrix$Year <- as.character(all_trials_matrix$Year)
```

2022-10-25 21:37 UTC, celiot-IDM commented
> @celiot-IDM this was what I mentioned in the meeting, it'll be good if we have a function to return mortality/fertility for all trials

@MeWu-IDM : Are you proposing that I turn the fragment I just sent (or something like it) into a built-in pacehrh:: function?

2022-10-25 22:01 UTC, MeWu-IDM commented
@celiot-IDM I was thinking something similar like SaveSuiteDemographics for mortality rates (SaveSuiteMortality)
I will discuss with @rhanIDM and see what type of output format is useful for researchers. I haven't looked closely at internal implementation of results, I thought it may save us time if the internal data structure is easier to work with.

2022-11-01 17:17 UTC, MeWu-IDM commented
this has been implemented in #210

2022-11-01 17:17 UTC, closed without merging